= Prefácio

Este livro foi desenvolvido a partir de uma série de palestras que dei
no decurso de alguns anos, principalmente no Mosteiro de Cittaviveka.
Nestas palestras explorei a relevância dos ensinamentos do Buddha sobre
o kamma para a prática da meditação. À primeira vista pode parecer que
estes dois tópicos não estão muito relacionados: o kamma é um
ensinamento sobre o comportamento, enquanto que a meditação,
aparentemente, é sobre a ausência da acção, não é verdade? Ou podemos
ter a ideia de que: ‘O kamma é sobre aquilo que eu fui numa vida
anterior, aquilo ao qual eu estou preso agora e aquilo que será o meu
renascimento. O kamma é acerca de ser alguém, enquanto a meditação é
acerca de não ser seja quem for.’ Não é assim. Espero que os textos que
se seguem, compilados a partir de palestras e que se tornaram ensaios,
ajudem a clarificar que os princípios do kamma ligam o comportamento
‘externo’ à prática ‘interna’ da meditação. E que a meditação é um
tipo de kamma – o kamma que leva ao final do kamma. Com efeito, ‘kamma
e o fim do kamma’ é um bom resumo daquilo que o Buddha tinha para
oferecer, como um caminho para o bem-estar e para o Despertar.

== Os três conhecimentos do Buddha

A experiência do Dhamma do Buddha tem a sua fundamentação nos ‘três
conhecimentos’, constatações que se diz terem ocorrido sequencialmente
ao Buddha, numa noite. Apesar de praticar meditação e ascetismo a um
nível muito elevado, o Buddha sentiu que esta prática não lhe tinha dado
frutos em termos da sua busca da ‘transcendência da mortalidade’. Mas
eis que, ao praticar mais tranquilamente, surgiram três compreensões e,
com estas, o seu objectivo foi atingido.

A primeira destas compreensões foi a consciência de vidas anteriores.
Este conhecimento transcendeu a definição mais fundamental das nossas
vidas – a divisão que ocorre na morte do corpo. Surgiu a compreensão de
que aquilo que é experienciado como uma ‘pessoa’, constitui uma
manifestação num processo em decurso, ao invés de um eu único e isolado.

Entrar em contacto com esta força vital subjacente não constituiu um
grande conforto: expandiu a questão da existência para além da duração
de uma única vida, para um purgatório existencial constituído por um
‘vaguear’ sem fim (_saṁsāra_). Contudo, por outro lado, existia uma
consciência que tinha transitado para essa panorâmica transpessoal. A
porta para a ‘transcendência da mortalidade’ tinha começado a
abrir-se.

A segunda compreensão foi que a ‘direcção’ desse vaguear não era
aleatória – este toma a sua direcção de acordo com a qualidade ética das
acções que a pessoa empreende. Surgiu o conhecimento que existem
energias que são disruptivas ou abusivas e que não sustentam a lucidez
ou a saúde. Por outro lado, existem energias que são harmoniosas, que
alimentam ou que estão claramente em sintonia. ‘Más’ e ‘boas’ (ou
inadequadas / deletérias / ‘escuras’ e adequadas / salutares /
‘luminosas’ em termos Budistas) não são, consequentemente, apenas
juízos de valor impostos por uma sociedade, mas sim referências a
energias que são palpáveis em termos psicológicos, emocionais e físicos.
A acção empreendida de acordo com uma energia sã constitui um suporte
para o bem-estar e para a harmonia, tal como o contrário tem o efeito
oposto. Este constitui o princípio de causa e efeito em termos éticos,
ou ‘__kamma-vipāka__’.

Contudo, _kamma-vipāka_ tem um significado mais profundo, que vai para
além de acções e resultados. Se a consciência cognitiva se apega a uma
acção (física, verbal ou psicológica) dá origem a uma consciência
cognitiva à qual é dada uma forma pessoal através desse mesmo apego.
Esta acção cria a impressão de um eu, que é o resultado dessa acção, e é
‘condimentada’ pela qualidade ética dessa acção. Dito de uma forma
simples: não se trata tanto de eu criar kamma mas sim do kamma ‘me’
criar. Desta forma _kamma-vipāka_ transcende a separação entre acção e
agente, mergulhando a consciência num campo de significado ético, onde
todas as acções formam e informam o ‘eu’, o ‘meu’, o ‘eu próprio’.

Da mesma forma, uma vez que o kamma surge numa maré de energia causal em
decurso, os resultados das acções podem ter lugar em vidas futuras. E
isto significa que o kamma nos prende ao processo de nascimento e morte
– algo que o Buddha recordou em termos dramáticos:

[quote, role=quote]
____
“Há muito que (repetidamente) experienciaste a morte de uma mãe… de um
pai… a morte de um irmão… a morte de uma irmã… a morte de um filho… a
morte de uma filha… perda relativamente a familiares… perda
relativamente a riqueza… perda relativamente a saúde… As lágrimas que
derramaste sobre a perda relativamente à doença enquanto transmigravas e
vagueavas durante este longo, longo tempo – a chorar e lamentar por
estares associado ao que é desagradável, estares separado daquilo que é
agradável – têm um volume que supera o total da água dos quatro grandes
oceanos.

Porque é que isto sucede? A transmigração surge de um começo que não é
passível de ser reconstituído. Não é evidente um ponto de começo, apesar
dos seres dificultados pela ignorância e algemados pelo anseio
continuarem a transmigrar e a vaguear. Assim, há muito, que experiencias
tensão, dor, perda, há muito que preenches os cemitérios – o suficiente
para ficar desencantado com tudo o que é fabricado, o suficiente para
ficar desapaixonado, o suficiente para ser libertado.”

https://suttacentral.net/sn15.3/en/thanissaro[SN 15.3]
____

Contudo, nesta admoestação existe igualmente a mensagem da possibilidade
da libertação deste _saṁsāra_: através do acto de limpar e de largar,
bem como da ‘cessação’ desses mesmos padrões de energia que
transportam a causa e o efeito – e o ‘eu’.

Estes últimos foram vistos a partir do terceiro conhecimento, que trouxe
a libertação das ‘coisas fabricadas’, das emoções, dos impulsos, das
sensações e das respostas que constituem a matéria-prima do apego. Este
conhecimento é a compreensão dos preconceitos subjacentes (_āsava_) que
condicionam o apego através do qual o _saṁsāra_ funciona.

== Renascimento e kamma

O _saṁsāra_ não se expressa por intermédio de um corpo ou uma
identidade. Os corpos mantêm-se dependentes das condições apenas durante
uma vida. A identidade – por exemplo filha, mãe, director, inválido,
etc. – surge como dependente de causas e condições. Aquilo que
anteriormente foi referido como ‘transmigração’ não é
‘renascimento’, mas o processo pelo qual uma corrente duradoura de
apego continua a gerar seres sencientes. Para além disso, esta corrente
não é algo que apenas ocorre na morte, mas que é alimentada de forma
contínua pelo kamma no momento presente. Através de uma tendência
denominada ‘devir’, o _kamma_ forma algo semelhante a um código
genético psicológico. Este código, que constitui o padrão da herança
cármica de cada indivíduo, é formado através de processos dinâmicos
chamados _saṅkhāra_. Tal como o código genético pessoal de cada um, o
_saṅkhāra_ retém os esquissos originais cármicos e, desta forma,
permanecemos de dia para dia, em termos relativos, a mesma pessoa.

Traduzido de forma variada como ‘formações’, ‘formações volitivas’,
‘fabricações’, etc., eu traduzo _saṅkhāra_ como ‘programas e
padrões’. Alguns destes programas são funções, tal como o metabolismo,
que se encontram ligados à força vital (_ayusaṅkhāra_); alguns são
veiculados pela consciência que é gerada a partir de vidas anteriores; e
alguns são formados através de interacções da vida presente. Os
programas mais significativos do ponto de vista da transmigração são
aqueles que enraízam o apego no nosso corpo e na nossa mente. Estas são
três ‘corrupções’ – a corrupção associada à informação dos sentidos
com sentimentos que vão desde o deleite à aversão; a corrupção de
‘devir/tornar-se algo’ que gera a sensação de um eu autónomo; e a
corrupção da ignorância que obscurece a verdade acerca do _saṁsāra_.
Estas corrupções são, na melhor das hipóteses, insatisfatórias e, na
pior, causadoras de tensão ou de dor, uma vez que programam de forma
contínua a mente para depender das características mutáveis da
informação sensorial e para formar uma identidade com base no terreno
instável dos estados de espírito. Devido a este desconforto existencial,
a consciência não-Desperta reage com hábitos de ganância, aversão e
confusão.

As boas notícias é que não estamos tão embutidos no _saṁsāra_ como
parece. Nem todos os aspectos da mente se encontram presos nas
corrupções. Nós podemos ‘ter consciência’ das corrupções. E são apenas
as corrupções que têm de ser eliminadas. A acção que constitui uma
preparação e que culmina com este corte é o Nobre Caminho, o Caminho
Óctuplo que o Buddha ensinou. Praticar este caminho é o kamma que leva
ao final do kamma.

Os ensinamentos sobre o kamma, sobre causa e efeito, proporcionam-nos um
Caminho para a libertação. De forma abreviada, quando sabemos como
funciona e temos as capacidades e as ferramentas para desconstruir os
programas da consciência cognitiva, podemos parar de construir o
_saṁsāra_. Mais detalhadamente, os ensinamentos do Buddha constituem um
guia para a acção sustentada, tanto no domínio externo como interno, em
que a prática no domínio externo – o de viver uma vida moral e receptiva
– estabelece as directrizes e encoraja as capacidades de forma a
esclarecer o domínio interno. Factores causais transpessoais, tais como
o estar presente, a investigação, a concentração e a equanimidade, podem
proporcionar o efeito de abolição da modelação das corrupções. Esta
prática, mais do que extrair a pessoa do _saṁsāra_, vai desligar o
processo do _saṁsāra_ para aquela consciência individual. O que resta
para aquele indivíduo pode ser resumido como um corpo e uma mente a
funcionarem durante esta vida, bem como uma consciência sem
preconceitos, que não participa na dinâmica da continuação dos
renascimentos.

== O kamma por detrás deste livro

Admito a existência de determinados enviesamentos. Existem muitas formas
de meditar e muitos professores experientes que podem constituir, neste
campo, um guia para os outros. Contudo, acontece com frequência que as
pessoas necessitam de ajuda na integração da atenção meditativa e da
realização interior nas suas vidas quotidianas. Isto, em parte, deve-se
ao facto da compreensão que as pessoas ganham nos retiros de meditação
não surgir do contexto da vida e das actividades do dia a dia, mas sim
de um ambiente especializado, tal como um centro de meditação. Nestas
condições, é dada uma atenção considerável a temáticas como a
consciência da respiração. Contudo, os temas que não são relevantes, em
termos imediatos, para a solidão e tranquilidade de estar sentado num
retiro, não recebem a atenção necessária para uma vida harmoniosa. As
relações interpessoais, quando saímos de um cenário de ‘ausência de
contacto, ausência de fala’ de um retiro, parecem difíceis de integrar
e, contudo, são parte da vida de todos nós. De igual modo, se
desenvolvemos a meditação no sentido de aceitarmos pacificamente aquilo
que está presente na nossa consciência, como é que tomamos decisões no
que diz respeito a escolhas relativas à nossa subsistência e
desenvolvemos planos sustentáveis para o futuro? De igual forma, será
que podemos obter orientação no tipo de desenvolvimento pessoal que nos
encoraja a sermos responsáveis, que nos permite aceitar, partilhar ou
questionar a autoridade, bem como tudo o resto de que a sociedade
necessita em termos de indivíduos com maturidade?

Infelizmente pode acontecer que as pessoas tenham experiências
‘espirituais’ válidas a um nível subtil mas permaneçam contudo
bastante alheadas aos seus próprios conceitos e ângulos mortos, em
termos de acções e de interacções pessoais. O que ajuda, na meditação e
na vida do dia a dia, é aprender a manter e a moderar o nosso propósito;
como sermos sensíveis e autênticos para connosco próprios e para com os
outros; e como valorizarmos e ajustarmos a qualidade de esforço que
colocamos nas nossas vidas. Tudo isto, e mais, se insere sob o tópico
relativo ao kamma. Desta forma, temos necessidade de conhecer muito bem
o que constitui um kamma cuidadoso, em termos de contextos internos
subtis e de contextos externos mutáveis mais óbvios.

Assim, saliento a importância da compreensão da causalidade, como uma
chave para o Despertar, uma vez que transforma a prática num caminho a
seguir na vida como um todo, em vez de uma técnica de meditação. Isso
enfatiza o facto de o _saṁsāra_ ser um hábito e não um lugar. Desta
forma, ‘sair do __saṁsāra__’ não envolve indiferença para com o mundo,
o corpo ou os outros, nem se refere à conquista de uma área de
território psico-espiritual refinado. Trata-se do abandono dessa
negatividade, dessa indiferença e dessa ânsia; e isso significa cultivar
e honrar o bom kamma. Por sua vez, esta constitui a base para a total
libertação do mal-estar pessoal. A beleza e a profundidade da explanação
do Buddha é, para mim, esta unidade: Verdade, Virtude e Paz podem surgir
a partir do mesmo foco.

Estas palestras não foram dadas em série, mas sim espaçadas no tempo.
Deste modo, foi necessário trabalhá-las em termos de revisão, de forma a
homogeneizar a linguagem, cortar as repetições e acrescentar material a
que os ouvintes, nessa mesma altura, tiveram acesso através de outras
palestras. Mesmo depois de tudo isto concretizado, pareceu-me que alguns
aspectos careciam de uma explicação mais completa. Consequentemente,
introduzi mais material escrito para além do material apresentado nas
palestras, de forma a ampliar este último. Pensei igualmente em colocar
algumas citações e notas do Cânone Pali e, como se estava a tornar
bastante teórico, intercalei os ensaios com algumas instruções de
meditação, breves mas relevantes. De qualquer modo, este livro não
constitui uma exposição passo-a-passo, mas sim um vislumbre de vários
pontos de interesse e uma revisão desses pontos a partir da perspetiva
do kamma.

Gostaria de agradecer a ajuda de Ajahn Thaniya, que selecionou e
comentou os textos, e de Dorothea Bowen, que realizou o trabalho de
revisão dos textos centrais. Ocasionalmente, o manuscrito circulou
também entre outros amigos contemplativos, com vista a obter críticas e
comentários: Ajahn Amaro, Ajahn Kovida, Ajahn Viradhammo e os amigos de
Ottawa, Irmã Cintāmani, David e Nimmala Glendining, Gabriel Hodes,
Douglas e Margaret Jones. Ajahn Kusalo ocupou-se da composição
tipográfica e do _design_. Este livro inclui ainda o bom _kamma_ de
muitas outras pessoas e faço votos que isto continue a guiá-las no
sentido de um maior bem-estar e liberdade.

Ajahn Sucitto +
Cittaviveka, 2007
