= Onde Existe uma Vontade Existe um Caminho

_Uma panorâmica sobre os ensinamentos do Buddha acerca do kamma_

[quote, role=quote]
____
_“E, bhikkhus, como é que uma pessoa vive
simultaneamente para o seu próprio bem e para o dos outros? Ela própria
pratica no sentido da remoção da cobiça, do ódio e da ilusão e encoraja
igualmente os outros a fazerem o mesmo.”_

_https://suttacentral.net/an4.96/en/thanissaro[AN 4.96]_
____

O que é o ‘kamma’ e qual a sua relação com o Despertar? Ora bem,
tomado como uma palavra, ‘kamma’ é a versão em língua Pali do termo em
sânscrito ‘karma’, que tem vindo a ser usado no inglês
coloquialfootnote:[E também no português coloquial (N.T.).] com um
significado semelhante a ‘destino’. Neste sentido, esta noção pode
apoiar uma aceitação passiva das circunstâncias: se algo corre mal
podemos sempre dizer que ‘era o meu carma’, querendo dizer que tinha
de acontecer. Onde a ideia de base realmente se perde é quando é usada
para pactuar com determinadas acções, como por exemplo ‘ser ladrão é o
meu carma’. Se este fosse o significado do carma tirar-nos-ia a
responsabilidade sobre as nossas vidas. Para além disso, não haveria
qualquer forma de nos orientarmos de modo a sairmos das nossas
circunstâncias ou da nossa história passada – que é aquilo em que
consiste o Despertar. Contudo, ‘kamma’, no sentido em que o Buddha
ensinou, significa acção adequada ou inadequada – algo que fazemos
agora. É o aspecto activo de um processo de causa e efeito conhecido
como _kamma-vipāka_, no qual _vipāka_ ou ‘kamma antigo’ significa o
efeito, o resultado de acções anteriores. E, em larga medida, vemo-nos
envolvidos nos resultados das nossas acções.

Não obstante, enquanto ‘acção’, o kamma apoia a escolha. Podemos
escolher as acções que vamos empreender. Causa e efeito regulam a
actividade dos vulcões, das plantas e dos sistemas planetários, mas o
kamma diz respeito especificamente aos seres que têm poder de escolha
sobre aquilo que causam – ou seja, o leitor e eu. Da mesma forma, nem
tudo o que experienciamos é devido ao kamma antigo (para além do que diz
respeito a termos nascido).[multiblock footnote omitted] Assim, se
adoecemos ou se formos apanhados num terramoto, não é necessariamente
porque tenhamos praticado más acções numa vida anterior. Em vez disso, o
kamma centra-se na nossa intenção ou ‘volição’
(_cetanā_)footnote:[Intenção/volição é kamma: por exemplo
https://suttacentral.net/an6.63/en/thanissaro[AN 6.63]. É importante
reconhecer que ‘intenção’ neste contexto não requer necessariamente
deliberação. _Cetanā_ refere-se à ‘inclinação’ ou à ‘intenção’ do
coração, que se encontra subjacente ao pensamento e alimenta a emoção.]
actual. Desta forma, os ensinamentos sobre o kamma encorajam um sentido
de responsabilidade relativa à acção – a responsabilidade de prestar
atenção às muitas escolhas conscientes e semiconscientes que realizamos,
em relação ao que fazemos. Isto significa que, neste preciso momento,
temos possibilidade de escolha sobre a forma como o futuro vai decorrer:
se nos vamos sentir contentes e tranquilos connosco próprios, ou
ansiosos e deprimidos, dependerá das nossas acções neste momento. E, de
igual forma, através das nossas acções neste momento, podemos ser
libertados do passado, do presente e do futuro. É isso que resulta do
Despertar para o kamma.

== Kamma físico, verbal e mental

‘Kamma’ significa ‘acção’, num sentido que vai para além do físico.
Inclui também a acção verbal – quer insultemos e gritemos com as pessoas
ou digamos coisas verdadeiras e fiáveis. E isso inclui o ‘discurso
interno’ do pensamento! Mas, na realidade, o kamma das nossas respostas
emocionais – o kamma ‘mental’ (ou ‘do coração’) – é o mais
forte.[multiblock footnote omitted] As respostas – e as propensões sobre
as quais elas se baseiam – regem as acções do corpo e do discurso,
originando igualmente resultados no domínio das emoções, das atitudes e
dos estados de espírito. De igual modo, as nossas acções físicas ou
verbais resultam apenas de convicções, pressupostos, interpretações e
atitudes (ou seja, todos provenientes da mente). Por si próprio, o corpo
não faz bem nem mal – estas qualidades éticas encontram-se enraizadas na
mente que inicia o acto físico. Passa-se o mesmo com a fala e o
pensamento: a linguagem é neutra – é a bondade ou a malícia da mente,
que utiliza a linguagem e os conceitos, que produz resultados felizes ou
infelizes.

Considerarmos o kamma sob este prisma motiva-nos a libertar a mente da
má vontade ou da cobiça, porque estas conduzem a acções verbais ou
físicas que deixam uma marca desagradável: geram rudez, apego e
obstinação e, mais tarde, preocupação, arrependimento e dúvida. Por
outro lado, acções e pensamentos baseados na compaixão proporcionam à
mente clareza e afecto. Daí os ensinamentos sobre causa e efeito: eles
são um lembrete para verificarmos, investigarmos e purificarmos os
estados de espírito associados à acção, seja ela qual for. Tal como as
nossas acções trazem conflito ou harmonia ao contexto em que vivemos,
controlar o kamma permite-nos ter um efeito positivo no mundo que nos
rodeia. Perceber o kamma desta forma também possibilita que percebamos
amplamente que o nosso bem-estar não é independente do modo como agimos
para com os outros.

== As dinâmicas do kamma

A lei do kamma define que um efeito ou resultado é inevitável a partir
de uma causa activa. Se eu ofendo e maltrato alguém hoje, isto tem como
efeito que essa pessoa se sente magoada e isso quer dizer que ela,
provavelmente, irá ser desagradável comigo no futuro. É igualmente
provável que essa acção tenha efeitos imediatos sobre a minha própria
mente: agitação e remorso. Ou pode acontecer que me habitue a agir dessa
forma: de modo que continuo a agir de forma ofensiva, desenvolvo uma
mentalidade insensível e perco amigos. Desta forma os efeitos
acumulam-se, tanto em termos de estados de espírito (ofensas e
remorsos), como também de estruturas comportamentais (um padrão ou uma
programação de ser egocêntrico ou de possuir uma língua afiada). O que é
verdadeiramente problemático são os ‘programas’, as ‘formações’ (ou,
em linguagem budista, _saṅkhāra_) em decurso. Estes padrões de
comportamento tornam-se parte da nossa identidade e, uma vez que não
conseguimos ver para além dos nossos próprios hábitos entranhados, estes
padrões e programas sustêm o girar, o _saṁsāra_, de causa e efeito.

Desta forma, se nos queremos libertar, é importante, controlar o modo
como estamos a funcionar. E isso é possível porque o processo
_kamma-vipāka_ forma circuitos de _feedback_ de sensações mentais de
tensão ou de agitação, ou de tranquilidade, que podemos contemplar e ter
em consideração. Para além disso, podemos responder de diferentes
maneiras ao resultado das nossas acções - de forma a que cada efeito não
venha a inevitavelmente gerar uma causa correspondente. Eis a escolha:
posso fazer uma pausa, sair do estado de espírito de irritação ou de
imprudência, prestar-lhe a devida atenção e tentar fazer melhor no
futuro. Este é o primeiro passo no sentido da libertação.

Os ensinamentos do kamma são mais facilmente acessíveis no contexto do
comportamento exterior. O Buddha viu que a clareza relativamente ao
comportamento proporciona uma via pragmática, através da qual o
sofrimento e a tensão podem ser evitados, e a paz, a confiança e a
clareza podem ser geradas. Assim, o Buddha falou de kamma escuro –
acções tais como assassínio, roubo, falsidade e abuso sexual, que
conduzem a maus resultados – e kamma luminoso – acções tais como
bondade, generosidade e honestidade, que fazem o inverso. O Buddha falou
igualmente de uma mistura de kamma escuro e luminoso – acções que
possuem algumas boas intenções mas que são conduzidas de forma
inadequada. Um exemplo disto seria termos o objetivo de proteger e
cuidar da nossa família, mas fazê-lo de um modo prejudicial para os
nossos vizinhos.

O kamma é também dinâmico: agimos de acordo com informação que recebemos
e, à medida que recebemos de volta os resultados agradáveis ou
desagradáveis, as nossas acções subsequentes vão sendo moldadas.
Contudo, uma vez que parte deste retorno não ocorre imediatamente e pode
mesmo levar anos a suceder, existem aspectos deste circuito de retorno
que são caóticos. Isto significa que o nosso ritmo de aprendizagem não
acompanha necessariamente o ritmo ao qual podemos desenvolver novas
acções. Estivemos a poluir alegremente a atmosfera durante décadas, até
se tornar claro o que se estava a passar e, por essa altura, outras
acções já tinham sido realizadas – estabeleceram-se indústrias e estilos
de vida dependentes de recursos não sustentáveis, o que torna a mudança
mais complicada.

Este ponto é significativo: encoraja-nos a esforçarmo-nos por clarificar
a consciência da mente e dos seus impulsos. É necessário que
investiguemos as nossas mentes e os programas mentais frequentemente e
de forma mais detalhada. Então aí é possível interromper o circuito de
retorno com informação que pára ou que modera os nossos impulsos. Esta
informação é o kamma que leva ao final do kamma e constitui o eixo dos
ensinamentos do Buddha.[multiblock footnote omitted] Ao ser plenamente
realizado, pode levar não apenas a mudanças no comportamento, mas à
libertação completa.

== Nascimento: a herança da causa e efeito

A libertação completa significa sair por completo do processo de causa e
efeito. Este processo é aquilo que estamos a experienciar neste momento.
Nascer é kamma antigo e trouxe-nos ao imbróglio da existência no domínio
da causa e efeito, com o potencial de continuar a girar nele. Tendo
herdado o efeito de sermos corpóreos, somos afectados por comida, saúde
e clima. E, juntamente com isto, vem o potencial para defender, procurar
comida e procriar. A mente está sintonizada para responder a tudo isto
de forma instintiva, com impulsos de luta, paralisação ou fuga, que
podem surgir num abrir e fechar de olhos. E com a mente vem a
consciência do envelhecimento, da doença e da morte. E, com isso, a
separação daqueles que amamos, com o efeito desagradável que isso tem em
nós; e ainda, o facto de sermos aparentemente impotentes para fazer seja
o que for acerca de tudo isto. Assim, o girar do _saṁsāra_ prende-nos no
seu movimento giratório.

O kamma antigo traduz-se igualmente em todos os programas sociais e
comportamentais que nos dizem como devemos funcionar em termos de
costumes e atitudes. Psicologicamente, experienciamos a necessidade de
pertença, de compreensão e de nos sentirmos em paz com as circunstâncias
nas quais estamos inseridos. Esta constitui a base para o kamma novo:
uma das nossas acções mentais mais contínuas é a de interpretação e de
arquivo de experiências, de forma a extrairmos significados e
propósitos. De igual modo, apanhamos muita informação das outras
pessoas, incluindo preconceitos e informação redundante, assim como bons
conselhos. Este kamma mental forma o programa, o modo de pensar, através
do qual interpretamos a nossa experiência presente. Instalado e
modificado ocasionalmente, este programa aplica, em qualquer momento,
uma interpretação da experiência presente para nos dizer ‘como algo
é’. E isto vai muito além da definição objectiva: ‘Será seguro, será
amigável, será permitido, serei valorizado ao adquirir isto’ e por aí
adiante – torna-se um filtro de impressões que nos ajuda a tomar muitas
decisões instantâneas nas nossas vidas. Contudo, qual a fiabilidade
deste processo crucial?

Surgem memórias que nos levam a ter determinada inclinação, surgem
condições físicas que afectam a nossa disposição, a duração da atenção
varia e o resultado de uma conversa que tivemos há uma hora atrás ainda
está a agitar os nossos corações. Entretanto o nosso contexto social
liga-nos aos efeitos das mentes das outras pessoas, cada uma com as suas
próprias interpretações e os seus mal-entendidos, de forma que também
somos afectados por isso. Os programas são transferidos, ou desencadeiam
outros programas, e as nossas mentes são apanhadas num turbilhão de
impressões, sendo que qualquer delas pode a qualquer momento despoletar
certos impulsos.

Então, a parte verdadeiramente crucial daquilo que herdamos é a
‘mente’ – uma consciência afectiva-receptiva complexa que transporta
um elevado potencial para mais kamma. Através da mente podemos estar
conscientes de algo, reflectir e desenvolvermo-nos de acordo com os
resultados daquilo que fazemos e dizemos. Podemos aprender. E, à medida
que as nossas respostas ampliam e intensificam a nossa experiência,
podemos ser criativos. Podemos concentrar-nos numa ideia e desenvolvê-la
numa invenção fantástica ou numa belíssima obra de arte. Contudo, por
outro lado, podemos ser assoberbados por uma emoção desenfreada.

Se a disposição é de desconfiança ou de ressentimento, podemos elaborar
pontos de vista maléficos sobre o mundo e cometer atrocidades. Há uma
grande amplitude de possibilidades: o Buddha refere muitos domínios
infelizes e infernais que resultam de acções imorais ou ‘kamma
escuro’. As boas notícias é que os domínios felizes e celestiais, onde
podemos nascer em resultado de kamma bom ou ‘luminoso’, são ainda mais
numerosos.footnote:[Tanto https://suttacentral.net/mn135/en/bodhi[MN
135] como https://suttacentral.net/mn136/en/thanissaro[MN 136] apontam
para diversos destinos localizados em reinos celestiais ou infernais
como o resultado de actos realizados nesta vida.] Seja como for não se
acaba tudo numa vida! Hoje em dia as pessoas gostam de interpretar estes
‘domínios’ cosmológicos como estados psicológicos – mas mesmo sob este
ponto de vista, o kamma, luminoso ou escuro, é acção que vai dar origem
a um estado de existência futuro. E, à primeira vista, parece que não
existe saída possível: experienciamos as nossas vidas como estando
inseridas num contínuo dinâmico que nos afecta e nos modela – tal como
nós o afectamos e modelamos.

Pensando bem, o processo de _kamma-vipāka_ é como o de um oceano que nos
pode elevar, engolir ou transportar em qualquer direcção. Funciona
através de uma interação contínua entre os efeitos herdados, à medida
que eles surgem no presente, e a gama de respostas consequentes e
tendências para agir. O passado não está morto: os seus efeitos
transportam potencial. E o futuro surgirá de acordo com a forma como
agimos com base nisso.

== Despertar para a causa e efeito

À primeira vista, esta perspetiva do kamma parece ser, não de
libertação, mas sim de aprisionamento. Mas quando se está na cela de uma
prisão, começa-se a investigá-la mais detalhadamente para ver, primeiro,
como é que se pode torná-la mais habitável e, depois, como sair dela.

Em primeiro lugar, se temos de gerar kamma, podemos, pelo menos,
determinar se este vai ser luminoso ou escuro. Lembre-se que existe a
possibilidade de escolha: o kamma depende da volição mental, ou da
intenção, quer se trate de uma intenção cuidadosamente ponderada, de uma
necessidade compulsiva ou de um reflexo psicológico. Neste sentido,
‘intenção’ não é apenas um plano deliberado. Com efeito, lá bem no
âmago do nosso enigma encontra-se o facto de nem sempre estarmos assim
tão claros relativamente ao que fazemos e às razões subjacentes. Podemos
estar a funcionar em modo automático, ou com uma atenção turva ou
desfasada, mas ainda assim a agir ou a sermos movidos pelo ‘empurrão’
de uma paixão ou hábito. Para muitos de nós, o problema principal não é
a intenção deliberadamente malévola, mas sim a acção baseada quer em
confusão, desatenção ou num mal-entendido. Muitos dos nossos problemas
têm origem no facto de estarmos ‘pre-ocupados’ ou emperrados em
hábitos. Dessa forma, não trazemos uma atenção clara às nossas acções.
Ou pensamos que as coisas estão bem e, portanto, não precisamos de nos
preocupar; ou que não estão bem, mas que não temos qualquer poder de
decisão sobre o assunto. Mas pelo menos existe sempre a escolha de
investigar o kamma, e é aí que começa a reviravolta.

Isto sucede porque a volição mental pode ser compreendida e bem
dirigida, se estivermos cientes dela com atenção e sabedoria. Podemos
olhar para os nossos pensamentos e impulsos, fazer uma pausa e
recebê-los de uma forma mais plena e, deste modo, sentir o tom luminoso
ou escuro que trazem à mente. Isto ajuda-nos a perceber como e quando
devemos agir. Por exemplo, o sentimento resultante de kamma luminoso
encoraja alguém que tenha tido o bom fortúnio de herdar riqueza ou
inteligência, a partilhá-la. Assim, essa pessoa irá fazer a melhor
utilização desse kamma antigo ao torná-lo kamma novo brilhante. Com
efeito, quando alguém não partilha o seu bom fortúnio, o efeito
agradável a ele associado estraga-se: as pessoas ricas que são egoístas
e complacentes, em geral, querem sempre mais ou tornam-se avarentas e
obcecadas consigo próprias.

Por outro lado, podemos estar a experienciar o efeito nefasto de sermos
agredidos ou magoados, ou de estarmos ansiosos, mas decidirmos não
cobrar isso a outra pessoa. Ou também podemos começar a investigar e a
acalmar essa disposição, e até a compreender o que causou esses efeitos.
Neste tipo de acção, a volição não progride para um estado futuro, mas
desenvolve-se no sentido de compreendermos o estado presente. Esta
compreensão não é uma questão de percebermos todos os porquês e motivos
do kamma: na realidade os detalhes das razões pelas quais experienciamos
uma determinada disposição, intuição ou impulso num determinado momento
são demasiado complexos para serem compreendidos, é como tentar
compreender que rio ou nuvem deu origem a qual gota de água no
oceano.footnote:[De acordo com
https://suttacentral.net/an4.77/en/thanissaro[AN 4.77], o funcionamento
preciso do kamma é um dos quatro ‘imponderáveis’. Ponderar sobre estes
leva à ‘loucura ou enfado’. Os restantes são: a dimensão do poder de
um Buddha, a dimensão dos poderes de alguém em estado de absorção
(_jhāna_) e a origem do mundo.]

O aspecto mais importante relativamente a compreendermos o kamma é
entrarmos nas correntes subjacentes da mente e alterarmos a maré dos
efeitos. E para fazermos isso é necessário que cultivemos uma
consciência firme, clara e não agitada por estados de humor e sensações.
Este reconhecimento, baseado na ‘Visão Correcta’, traz o ‘Propósito
Correcto’, a activação do Caminho Óctuplo que nos liberta do sofrimento
e do stress.[multiblock footnote omitted]

Um aspecto que se torna evidente em relação à corrente da mente é que
seja em que sentido for que ela esteja a fluir, temos a tendência a
ficar presos nela. Queremos proteger e manter um estado feliz e
sentimo-nos mal relativamente ao seu eventual declínio ou
desaparecimento – a nossa identidade fica baseada nesse estado. Por
outro lado, sentimo-nos encalhados e desesperados relativamente aos
estados de infelicidade. Desta forma, todo o kamma origina, define e nos
enquadra em termos psicológicos. Portanto, até o bom kamma confere uma
certa desvantagem, pois ainda implica um investimento na área do kamma.
Nessa área, a roda da sorte pode girar no sentido descendente: podemos
ser atacados e certamente adoeceremos, sentiremos dor e enfrentaremos
separações. Podemos igualmente ser arrebatados por alguma paixão ou
impulso avassalador e fazermos algo do qual nos arrependamos para o
resto da vida. Assim, o Buddha apontou para uma melhor opção: sair desta
arena do kamma, aprofundando a consciência para além do alcance do kamma
e do _vipāka_. Este é o objetivo que leva ao Despertar e à total
libertação.

== Kamma e o ‘eu’

No seu verdadeiro sentido, a libertação do kamma é a libertação da mente
do ciclo de causa e efeito. É um processo de nos distanciarmos mental e
emocionalmente de qualquer estado e de o ver apenas como um estado, sem
reacções e atitudes. Esta capacidade simples, que muitos de nós
conseguimos ter ocasionalmente, é aquilo que desenvolvemos na prática
budista. De uma forma mais radical, significa distanciarmo-nos do
programa que afirma que ‘a minha vida encontra-se preenchida se eu
tiver ou estiver num determinado estado… neste ou noutro mundo’. Esta é
a perspetiva que perpetua o kamma. Quando esta perspetiva constitui a
lente através da qual vemos, iremos continuar a procurar, ou a imaginar,
um determinado estado subjetivo imutável no qual nos encontramos,
podemos vir a estar, ou que poderemos possuir. Já alguém, alguma vez,
encontrou algum estado com estas características? Esta ‘perspetiva de
si próprio’ agarra-se aos corpos, aos sentimentos, às noções, aos
programas mentais e à informação sensorial sob a forma ‘isto sou eu,
isto é meu, isto sou eu próprio’. Mas já encontraram algum estado no
qual podem ficar para sempre e que nunca vos desilude?

E quem é este ‘eu’ que pode possuir alguma coisa e o que é que ele ou
ela poderá ser? Como é que ‘eu’ posso ter posse das emoções, se as
agradáveis se vão embora quando ‘eu’ não quero, e as desagradáveis
instalam-se sem serem convidadas? Como é que ‘eu’ posso ser os meus
impulsos, as minhas ideias ou as minhas disposições se, quando estes
surgem, condicionam-se entre eles e desaparecem como se de cúmplices se
tratassem? Não podemos dizer que os sentimentos constituem um ‘eu’
permanente, uma vez que eles vão e vêm, e alteram-se. Nem sequer podemos
chamar isso de propensão para sentir ‘um eu’, uma vez que também isso
se encontra dependente de estarmos acordados ou adormecidos, atordoados,
desatentos ou hipersensíveis. Para além disso, os significados pessoais
que projectamos na vida e as reacções e as respostas psicológicas que
são as nossas impressões digitais, estão também sujeitas a alterações. A
dinâmica deste processo é tão contínua, que dá origem a uma sensação de
solidez, mas não se consegue encontrar uma essência ou uma entidade
central permanente.

Se aprofundarmos este tópico, algo que seja ‘eu’ teria de ser
independente – apenas ‘eu’ e não parte de outra coisa. Mas a
existência e constituição do corpo, por exemplo, encontra-se dependente
dos pais e da comida, bem como de muitos outros factores. Não surge de
forma independente. Quando cortamos o cabelo ou as unhas, não perdemos o
sentido de ‘eu’, de forma que o ‘eu’ não pode estar associado à
corporalidade. E os sentimentos e a propensão para sentir não estão
dependentes de ‘algo’ mais? Vemos algo, sentimos algo – que tipo de
ver e de sentir poderia acontecer sem um objecto? Para além disso, o
‘eu’ não pode estar associado a estados e actividades mentais – estes
não surgem dependentes de estados físicos ou de outros estados ou outras
actividades mentais? Então, mais uma vez, se corpo, sentimentos e
informação sensorial fossem o meu ‘eu’, certamente que eu poderia
decidir ‘que sejam desta forma e não de outra’. Mas, efetivamente,
eles seguem o seu próprio caminho, o caminho da ‘causa e efeito’.
Então o que é o ‘eu’? E o que é que se passa aqui?

Podemos não conseguir encontrar algo ao qual chamar ‘eu’, contudo
experienciamos ‘ser algo’ de forma contínua; temos um sentimento
contínuo de ‘eu sou’. Como é que isto acontece? Devido à consciência –
cuja função normal é discriminar a experiência, em termos de um sujeito
e um objecto separados. Mas sujeito e objecto constituem inferências e
não realidades, e eles estão dependentes um do outro – não podemos ter a
sensação de um sujeito sem um objecto e vice-versa. Agora, quando a
consciência mental se dirige para a nossa dimensão interna, subjectiva,
mais uma vez separa sujeito de objecto, com uma inferência de ‘eu’,
como o propagador, e de ‘mim próprio’, como aquele que herda os
estados de espírito, as disposições, os pensamentos e tudo o resto. (Tal
como em ‘aqui estou eu a sentir-me confundido comigo próprio, porque
esta atitude não parece minha – estou-me a sentir fora de mim neste
momento’.)

Cada sensação, cada pensamento, cada sentimento que ocorre é
classificado como ‘aquilo que sou – isto é meu’ (apesar de mudarem e
desaparecerem); ou então mantemos a noção que ‘eu não sou assim’
(apesar de ‘eu’ ser definido em termos de informação que recebo e que
me afecta). Qualquer uma destas duas actividades psicológicas
instintivas de ‘eu ser’ (‘eu sou isto’ ou ‘eu sou algo que não
isto’) determina continuamente um sentido de eu próprio, de formas que
geram ainda mais uma autodefinição específica. Contudo, uma vez que
‘eu’ não consigo agarrar-me àquilo que quero e não consigo escapar
daquilo que não quero, a disposição subjacente do ‘eu’ fica inquieta e
insatisfeita. Persisto em encontrar o estado bom…, mas ainda não é bem
este. Assim, existe mal-estar. A libertação deste mal-estar e desta
tensão é, assim, sinónimo da nossa Libertação do ‘eu’ insatisfeito.

== Desenvolver-se a si próprio para se libertar do ‘eu’

A forte tendência para manter um ‘eu’ – denominado ‘tornar-se/devir’
ou ‘ser’ (_bhava_), encapsula o sentido do ‘eu’ e de ‘mim’ como
uma noção, uma impressão de si próprio que perdura como um ponto de
referência para a minha mente, independentemente daquilo em que ela
tenha estado envolvida. Desta forma, este ‘eu’ não é uma entidade mas
sim um padrão, um ‘programa de construção de si próprio’ (_ahaṁkāra_),
constituído por comportamentos emocionais e psicológicos. Estes dão
origem à sensação de que: ‘esta é a forma como funciono, estas são as
minhas opiniões, esta é a minha história’ e, consequentemente, existe a
impressão de ser um ‘eu’ neste e naquele estado, com estratégias no
sentido de continuar dessa forma, de a incrementar ou de sair dela. Mas
tudo isto não constitui uma identidade, algo fixo, sendo sim um processo
de ‘ser isto e tornar-se aquilo’. ‘Tornar-se’ (ou ‘devir’) é o
programa central por detrás do kamma. É a razão pela qual existe tanta
actividade mental. Mas devido a ser uma actividade, não pode parar.
Contudo, este ‘devir’ está enraizado e é instintivo: não pára através
do raciocínio. Como instinto que é, tem de ser travado no âmago do
coração, sendo este um processo que envolve conduzir o impulso da
intenção a clarificar o ponto de vista que cria o ‘eu’.

Primeiro temos de criar força, perícia, capacidade. Assim, muitos dos
ensinamentos do Buddha favorecem o ‘devir’ em termos de nos tornarmos
mais claros, mais estáveis, mais afáveis.footnote:[Ou seja, aquele que
se desenvolve faz com que estados positivos, tais como a calma e a
bondade, se concretizem. Alguém assim tem: “realização em termos de
virtude; de desejo; de si próprio; de diligência; de atenção
cuidadosa.” https://suttacentral.net/sn45.71-75/en/bodhi[SN 45.71]]
Geramos bom kamma através de actos de generosidade, bondade e através do
abandono dos comportamentos que causam dano. Tornamo-nos pessoas mais
calmas, mais inteligentes. A visão correcta encoraja consciência dos
resultados daquilo que fazemos, consciência de partilharmos este mundo
com outros e consciência da importância do nosso domínio interior,
psicológico, sobre o domínio do contacto dos sentidos. Se o sentido mais
profundo de realização, através da compaixão e da calma, se estabelece,
podemos então largar o ‘conseguir, ganhar e agarrar’ – principais
causas de tensão. Podemos divergir da necessidade de eficiência a curto
prazo, de conveniência, de sucesso, de conforto e de atracção sexual.
Estaremos, então, no caminho certo para a libertação.

Consideremos o cenário social: no ocidente, muitos de nós podemos viver
com conforto físico, contudo, por estamos constantemente a ser
confrontados com comodidades mais refinadas ou com alterações constantes
nos padrões de comparação, não existe um grande contentamento. E existem
também pressões sociais e de grupo. Uma pessoa pode muito bem sentir que
o seu emprego está em risco se a roupa que está a usar não for a
‘correcta’, de forma que tem de ter este aspecto em consideração. As
pessoas podem tornar-se deprimidas, mesmo neuróticas, se os seus corpos
não estiverem à altura dos padrões actuais de beleza, ou se as suas
personalidades não forem suficientemente vivas, cínicas ou sórdidas
(dependendo da moda). Queremos evitar perder boas oportunidades e
receamos a solidão de não ter amigos. Por isso pode existir um
sentimento de nervosismo ou de insegurança relativos a falta de
adequação, que nos privam de um sentimento de confiança no nosso valor
inato enquanto seres humanos.

Então, somente por causa disto, é importante que sintamos e nos
definamos como ‘estando’ afastados destas correntes, mais que não seja
para chegarmos a uma base mais firme. E o que realmente nos ajuda é
acalmar e apaziguar a mente, e desenvolvermo-nos naquilo que confere
maiores benefícios, vivendo a nossa vida com autenticidade. Podemos
cultivar uma simplicidade de necessidades e um sentido de sinceridade e
de integridade. Podemos ter contentamento através do reconhecimento do
bem em nós próprios e nos outros. As pessoas têm problemas e defeitos,
mas é sábio honrar a bondade que todos temos. É igualmente sensato
encarar com compaixão as nossas tendências no sentido da reactividade e
da confusão, isto porque a forma como dispomos a nossa atenção cria o
âmbito no qual a mente habita. De modo que, se pudermos começar por
experienciar clareza e empatia relativamente a nós próprios e aos
outros, damos por nós a viver de uma forma mais grata e equilibrada,
encorajando o desenvolvimento da bondade. Assim, podemos dirigirmo-nos
para o bom kamma, desenvolvendo uma base que constitui um real apoio
para o nosso bem-estar.

Trabalhar desta forma com as impressões da mente pode trazer mudanças
radicais na vida. Descobrimos que o factor de ‘saber bem’, de
agradabilidade, requerido pelo nosso sentido de ‘eu’ é adquirido de
modo muito mais completo através da propensão para um comportamento
ético e de compaixão. As qualidades que surgem destas propensões são
altamente nutritivas. Trata-se de cultivar o ‘eu’ de uma forma
correcta e constitui um aspecto essencial da prática do Dhamma. A partir
daqui compreendemos que podemos realizar escolhas com significado nas
nossas vidas, o que nos confere a capacidade de sentir o potencial da
nossa condição humana e nos encoraja a investigá-la mais profundamente.

== Discernimento e ‘não-eu’

Todo este bom kamma baseia-se no cultivo da mente, sendo que a
capacidade de acalmar e serenar a mente através da meditação é outra
forma de kamma ‘bom’ ou ‘luminoso’. De uma forma geral, existem dois
temas principais de meditação para estabilizar a mente: o de manter uma
atenção firme e o de trazer bem-estar ao coração. Estes temas focam-se
em efeitos benéficos e alegres, que proporcionam conforto imediato à
mente, e desligam os programas verdadeiramente destrutivos de
ressentimento, depressão, ansiedade, etc. De modo que nos tornamos um
‘bom eu’, com uma mente calma e aberta. Isso torna possível a
investigação sobre como o ‘eu’ ocorre e como se pode abdicar
totalmente do ‘devir’. Este é o cultivo da ‘realização interior’.

Estes dois aspectos do cultivo mental – desenvolver um ‘bom eu’ e
libertarmo-nos da perspectiva do ‘eu’ – andam lado a lado. Quando
conseguimos desenvolver um ‘bom eu’, podemos investigar o que está na
sua base e compreender que se fundamenta em estados que dependem de bons
programas, tais como bondade, determinação ou concentração. Não são
inerentemente seus ou de qualquer outra pessoa. Esta é a visão da
compreensão: as causas e condições dão origem a efeitos felizes ou
lamentáveis. Para além disso, os resultados felizes surgem de forma mais
pronta e constante se a mente não se encontrar preocupada em afirmar ou
negar um ‘eu’ que tem ou não esses resultados. Esta visão do ‘eu’
como sucesso ou fracasso cria uma pré-concepção, na qual as mentes ficam
encalhadas e, quando isto acontece, sente-se tensão, surgindo as
condições para agitação, incerteza, anseio, desânimo, etc.

Mas temos de lidar com a pespectiva do ‘eu’, compreendê-la e revelá-la
como uma série de programas que criam tensão. Tentarmo-nos livrar de um
‘eu’ requer intenção (e até uma atitude de indiferença gera efeitos).
Qualquer abordagem niilista transporta sementes de kamma escuro: querer
ser nada (_vibhava_) continua a partir do princípio de que somos algo, e
envolve a intenção de aniquilação. Tudo isto torna-nos menos confiantes
e generosos nas nossas acções e relacionamentos. Pelo contrário, o
processo de Despertar altera a enfâse na construção do ‘eu’ para uma
enfâse no apoio e no apreço pelo equilíbrio mental. Temos necessidade de
sentir essa estabilidade interior, no presente, de forma a sermos
capazes de largar os pressupostos e preconceitos do passado e a
necessidade de devir, que luta ou anseia pelo futuro. E é através deste
abandono do devir que encontramos um ponto de tranquilidade – onde o
kamma antigo deixa de afectar a mente.

== Prática diária

Tal como todos os que praticam não tardam a compreender, este cultivo
introspectivo tem de remar contra a corrente de grande parte da cultura
dominante. Temos uma enorme indústria de distracção que nos encoraja a
empregarmos o tempo a evadirmo-nos de onde estamos – ler alguma coisa,
comer alguma coisa, olhar distraidamente para a televisão – e isto
afasta-nos do acto de observar e cultivar a mente. E também nos coloca
frequentemente em situações nas quais não recebemos qualquer tipo de
informação responsável. As distrações parecem oferecer uma saída fácil
da tensão, mas não nos fazem muito bem. Trata-se de uma forma de ignorar
os efeitos negativos com os quais não queremos ou não sabemos lidar, mas
que não os remove totalmente. Por exemplo, digamos que depois de ter
tido um dia stressante, teve de conduzir no meio do ambiente irritante e
agressivo do trânsito: todo aquele contacto aleatório rápido e
potencialmente arriscado agita o sistema nervoso. De forma que chega a
casa a sentir-se tenso e desgastado, e então surge o reflexo para
contactar algo agradável ou fácil. Talvez apenas se atire para o sofá e
coma qualquer coisa, beba algo ou veja qualquer coisa na televisão,
fique vagamente descontraído ou divertido e dependente de apoios
exteriores. Neste cenário a mente torna-se fraca e subdesenvolvida e,
gradualmente, torna-se necessário que as formas de distracção sejam cada
vez mais fortes. Se permitirmos que este padrão persista, podemos passar
uma vida a tornarmo-nos psicológica e emocionalmente fracos.

A maior parte de nós precisa de lembretes de forma a não sermos
contagiados pela disposição do contexto social indiscriminadamente e
para nos lembrarmos que podemos conseguir sair do programa da rotina
diária. Para começar, tenho sempre uma imagem do Buddha no espaço onde
habito, num pequeno altar, ou em qualquer sítio onde possa estar em
contacto com ela. É algo que me lembra o valor de estar plenamente
presente – encoraja-me a fazer uma pausa, reconhecer e reagir ao estado
em que me encontro, seja ele qual for. Recorda-me que a primeira
prioridade é criar algum espaço na mente, em vez de fazer com que o
cultivo da mente seja ainda mais outra coisa para me ocupar. Se o dia é
uma roda-viva a fazer e a resolver coisas, é bom aprender a moderar
essas mesmas volições.

Quando estamos num estado emocional instável, a resposta mais adequada
pode ser apenas receber o que estamos a sentir no momento presente com
alguma clareza e simpatia – sentarmo-nos tranquilamente e permitirmos
que as coisas passem através de nós. Seja qual for o estado, a reacção
inicial tem de ser de permanecer presente e cultivar espaço. Mas causa e
efeito funcionam de uma forma que faz com que quando ficamos sem agir ou
suprimir o nosso estado mental actual (mesmo que seja só por cinco
minutos), o resultado é um determinado tipo de tranquilidade e de
diminuição de pressão. Então começamos a reconhecer uma sanidade
natural, uma semente do Despertar, que está presente quando ‘o fazer’
cessa. Não está muito distante. Mas nós necessitamos de entrar em
contacto com ela e encorajá-la.

== É sempre possível

A constatação mais significativa que resulta de uma pausa de cinco ou
dez minutos dos aspectos de ser e devir, é que as coisas param por elas
próprias. Não quero com isto dizer que uns minutos de descontração sejam
o fim do kamma e a alvorada da Derradeira Verdade, mas mostram-nos que a
mente pode ter uma direcção diferente, em vez de avançar (ou recuar) aos
ziguezagues. A mente pode ser aberta, e nessa abertura, todo o cenário
se altera: experiencia-se a consciência mental como um campo no qual
pensamentos, disposições e sensações vêm e vão. E podemos testemunhar
esse conteúdo mental, em vez de agirmos em função dele. Para além disso,
uma boa parte do conteúdo mental cessa quando não existe a perspectiva
de que temos de agir, resolver ou mesmo parar, e não existe o ‘eu’
atarefado a tentar urgentemente manter esse conteúdo mental
activado.[multiblock footnote omitted] Esta é uma descrição resumida da
forma como o kamma do desenvolvimento leva ao fim do kamma.

Mas trata-se de um processo subtil. Os pensamentos e as disposições não
param por tentarmos fazê-los desaparecer – essa tentativa constitui mais
volição, mais kamma. Eles param quando o programa de identificação, a
base do ‘devir’, não é posto em funcionamento. Vale a pena
lembrarmo-nos disto porque quando consideramos a complexidade dos
circuitos de _feedback_ de causa e efeito, é fácil perceber que seria
necessário um muito complexo processo de desenlace e acalmia. Mas um
vislumbre de como ocorre a cessação ao não darmos apoio à energia e
perspectiva da identificação, mostra-nos que a forma de sairmos do
mal-estar e da tensão é simples e directa. E isso encoraja-nos a criar
ocasiões nas quais podemos levar a não-identificação a níveis mais
profundos da nossa actividade psicológica. Isto é conseguido através do
processo contínuo de meditação, mas todos podemos e precisamos de apoiar
esse processo no dia a dia. Não precisamos de beber a água onde nadamos.

Não bebermos do oceano do _saṁsāra_ significa controlar e restringir a
atracção dos sentidos, controlar e pôr de lado os programas normais
dominantes e cultivar a atenção e a consciência plenas. Ou seja,
trata-se de um caminho para a vida, o Caminho Óctuplo. E isto decorre da
Visão Correcta e da Intenção Correcta, não das perspectivas do ‘eu’,
do destino ou através de sistemas e técnicas automáticas. Ao seguir esse
caminho, constatamos que não estamos tão incorporados e presos no
_saṁsāra_ como pareceria. Para começar, na realidade nunca conseguimos
tornarmo-nos algo durante muito tempo. Claro que atravessamos períodos
de agitação e de tensão mas, com a prática, existem períodos de alegria
e de bom-humor e, à medida que nos tornamos mais astutos a levarmos a
mente em consideração, o hábito de nos agarrarmos a determinados estados
abranda. Identificamo-nos cada vez menos com este ou com aquele estado e
isso reduz a tensão e a agitação.

Deste ponto de vista, a vida humana constitui uma grande oportunidade.
Independentemente dos efeitos que herdamos, podemos sempre agir de forma
adequada e cultivar a mente. Podemos sempre encaminharmo-nos no sentido
da bondade, da felicidade e da libertação.

== Meditação

_Sentar-se tranquilamente_

Sente-se confortavelmente num local tranquilo. Descontraia os olhos mas
deixe-os abertos ou semicerrados, com um olhar descontraído. Esteja
consciente da sensação dos globos oculares a descansar nas respetivas
cavidades (em vez de focar o olhar naquilo que vê). Esteja sensível à
tendência dos olhos para não pararem quietos e descontraia-os
constantemente. Como alternativa, pode achar útil deixar o olhar
descansar, de forma descontraída, num objecto propício, tal como uma
paisagem distante.

Seguidamente leve a atenção para as sensações nas suas mãos, depois para
o maxilar e para a língua. Veja se também estas podem deixar, por um
momento, de estarem sempre apostos para entrar em acção ou para se
defender. Deixe a língua descansar na parte inferior da boca.
Seguidamente percorra, com essa atenção relaxante, uma área desde os
cantos dos olhos até à volta da cabeça, como se estivesse a tirar um
lenço. Deixe que o couro cabeludo se sinta liberto.

Deixe os olhos fecharem-se. À medida que descontrai a cabeça e a cara a
toda à volta, traga essa qualidade de atenção, lentamente, gradualmente,
mais abaixo para a garganta. Solte essa zona, como se permitisse que
cada exalação soasse como um zumbido inaudível.

Mantendo o contacto com essas zonas do corpo, ciente do fluxo de
pensamentos e de emoções que passam pela mente. Oiça-os como se
estivesse a ouvir a água a correr ou o mar. Se sentir que está a
reagir-lhes, leve a atenção para a próxima expiração, continuando a
descontrair através dos olhos, da garganta e das mãos.

Se quiser expandir o processo, percorra com a sua atenção o corpo até às
plantas dos pés e, desta forma, construa toda uma sensação de à-vontade
no corpo.

Mantendo a consciência da presença do seu corpo como um todo, pratique o
distanciamento ou largue quaisquer pensamentos e emoções que surjam. Não
lhes acrescente nada, deixe-os passar. Sempre que fizer isso, repare na
sensação de espaço, mesmo que breve, que parece estar aí presente, por
detrás dos pensamentos e dos sentimentos. Entre em sintonia com essa
tranquilidade.

Ao sentir essa tranquilidade, acolha-a. Em vez de exigir ou tentar
atingir um estado de calma, crie uma prática na qual serenamente oferece
paz às energias que o atravessam.
