= Kamma Luminoso

_Apoio para a atenção_

[quote, role=quote]
____
_“Aquele que faz o bem, alegra-se no presente e no
futuro, em ambos os mundos. Relembrando as suas acções puras, ele
alegra-se e exulta”_

_https://suttacentral.net/dhp1-20/en/buddharakkhita[Dhammapada 16]_
____

Nas duas últimas semanas, uma imagem do Buddha tem sido criada neste
mosteiro pelo Ajahn Nonti, um escultor tailandês que veio cá praticar
este acto de generosidade. Tem sido um bonito acontecimento, pois a
imagem do Buddha tem sido feita de forma amigável e agradável. Muitas
pessoas têm tido a oportunidade de participar e ajudar. Ontem estavam
nove pessoas a trabalhar na imagem, a alisá-la. Não é uma imagem assim
tão grande, contudo estavam nove pessoas a trabalhar nela, sem chocarem
umas nas outras e a disfrutarem o trabalho em conjunto.

== Kamma brilhante e kamma escuro surgem no coração

Nove pessoas a trabalhar em conjunto de forma amigável e agradável, é um
bom acontecimento. Para além disso, tudo isto tem um carácter voluntário
e não aconteceu devido a qualquer combinação prévia: as pessoas
interessaram-se pelo projecto e reuniram-se para colaborar nele. Neste
caso, isto deve-se ao que o Buddha representa e ao facto de as pessoas
gostarem de aderir a causas beneméritas. É essa a magia do bom kamma:
surge quando fazemos algo com significado a longo prazo e, também, por
agirmos de uma forma que nos traz felicidade, em vez de ser algo intenso
ou compulsivo. O kamma (acção intencional ou volitiva) tem sempre um
resultado ou um resíduo e, neste caso, é óbvio que o bom kamma está a
ter bons resultados. Há um resultado imediato pois as pessoas sentem-se
contentes ao trabalharem em conjunto. E existe um resultado a longo
prazo: estão a fazer algo que irá beneficiar outras pessoas.

Dentro de alguns dias contamos instalar a imagem do Buddha na sala de
meditação. É uma imagem que me faz sentir bem quando a contemplo. Tem
uma qualidade suave e convidativa, que cria um sentimento de boas-vindas
e de descontração - é um lembrete muito bom para a meditação. Por vezes
as pessoas podem ficar bastante tensas relativamente à ‘iluminação’ e
isso faz surgir preocupações, necessidades e exigências. Mas, com
frequência, o que necessitamos é de nos sentirmos bem-vindos e
abençoados. Isto constitui uma reviravolta significativa da nossa forma
habitual de pensar. Mas quando estamos sentados num sítio no qual
sentimos que confiam em nós e onde estamos rodeados por benevolência,
podemos nos abrir à experiência. E, à medida que abrimos os nossos
corações, podemos sentir a clareza da presença e consolidarmo-nos à sua
volta. Esta firmeza que surge da suavidade é aquilo que a imagem do
Buddha representa. Ela lembra-nos que existiu um Buddha histórico, cujo
Despertar ainda brilha através dos tempos - mas quando isto se apresenta
como uma impressão do coração e não apenas como um excerto de história,
traz consigo muito mais ressonância. Então a imagem serve como uma
reflexão directa sobre o sentimento associado ao bom kamma.

Nas escrituras, o bom kamma é geralmente denominado ‘kamma claro’, por
oposição ao ‘kamma escuro’. ‘Claro’ quer dizer que experienciamos
clareza e elevação. Mais do que uma ideia, a claridade é uma tonalidade
e não um julgamento (bom ou mau, certo ou errado). Tem beleza. A palavra
‘claridade’ tem o sentido de algo a abrir, de suavidade e de alegria –
tem estas tonalidades. Enquanto que ‘escuro’ implica estar fechado,
contraído e sem esperança. De forma que isto é algo a ser investigado
internamente: a tonalidade das acções que empreendemos e o contexto que
geramos à nossa volta são luminosos? Mesmo quando admitimos alguma
verdade dolorosa acerca das nossas acções, não existe uma certa
claridade, uma certa dignidade, quando o fazemos de bom grado? Procurem
a claridade em situações nas quais nos apresentamos assim, e não em
termos de facilidade superficial ou de serem bons por obrigação: a
atitude subjacente àquilo que dizemos e pensamos – é clara ou é escura?
Mais do que o encanto ou a obediência, essa tonalidade é a atmosfera, o
sítio onde os nossos corações residem.

== Mente-órgão e mente-base

A energia do kamma circula através de três canais. O primeiro é o corpo:
agimos fisicamente. O segundo é a faculdade da fala (que inclui o
‘diálogo interno’ do pensamento). O terceiro é a mente - o sentimento
de ser afectado e de responder. Em inglês (e em português), o termo
‘mente’ abrange tanto a actividade conceptual como o sentimento
afectivo que dá à mente o estado ou disposição global. Mas na língua
Pali existem duas palavras:

* _mano:_ refere-se à mente enquanto órgão que se concentra na
informação recebida através de qualquer um dos sentidos. Esta função
denomina-se ‘atenção’ (_manasikārā_). A mente-órgão pode igualmente
definir e articular – faz-nos recordar e produz conceitos. Em termos de
tonalidade é bastante neutra, não é alegre nem triste. É a racionalidade
que define: ‘Aquilo é aquela tal coisa, desta forma, assim e assado’.
* _citta:_ refere-se à mente enquanto ‘coração’, a base que recebe as
impressões que a atenção lhe proporcionou. É afectada em termos de
prazer e de dor, o que se manifesta em estados de espírito de variáveis
graus de alegria e de tristeza. De igual forma, _citta_ forma sinais,
percepções ou ‘significados sentidos’ (_saññā_) relativos às
impressões que recebeu e que a afectaram. Então, podemos avaliar nova
informação com base nos sinais que já estão definidos: uma bola cor de
laranja de uma determinada dimensão e textura é provavelmente uma
laranja. Certamente não será uma pessoa ou um tigre. Este significado
possui nuances que assim determinam outra função mental: a intenção – a
mente move-se no sentido do objecto voluntariamente ou com o interesse
de o comer. A intenção ou volição ocorre como uma resposta a sermos
afectados e é assim que surge o kamma mental.

A mente-base ou a mente-órgão funcionam da seguinte forma: quando a
_citta_ é afectada, o seu órgão, _mano_, pode então produzir um conceito
mental adequado, de modo que, tendo reconhecido um objecto, podemos
então dizer ‘Isto é um cão; isto é uma campainha’. A mente-órgão pode
igualmente inspecionar a mente-base e definir as suas disposições. Tudo
isto constitui a acção da _mano_. O problema é que as pessoas podem
pensar em praticamente tudo, com base no que vêem, ouvem e em ideias,
sem reflectirem necessariamente sobre a forma como o coração foi
afectado. Existem bastantes discussões sobre a verdade, a paz, o amor, a
liberdade e outros grandes ideais, porque as paixões ou os receios se
misturam com estas noções. Contudo, não se sente seja o que for ao nível
da faculdade _mano_. E, assim, este não reconhecimento do preconceito
subjectivo é denominado como ‘verdade objectiva’. (!) Mas para
sabermos plenamente, não apenas pensarmos ou termos alguém que nos diga,
e sim sentirmos realmente a qualidade de bondade, amor e por aí fora,
temos de entrar neste coração e purificá-lo. Desta forma, o _kamma_ mais
importante para aprofundarmos a nossa verdade, a nossa paz e a nossa
liberdade, começa ao darmos uma reviravolta à nossa mente – fazendo com
que a _mano_ examine a _citta_.

== Significados sentidos

Quando olhamos para aquilo que provoca os nossos impulsos e acções,
percebemos que estes surgem a partir de sentimentos e tendências do
coração. Estes sentimentos e tendências mentais estão ligados às
percepções ou ‘significados sentidos’, tais como ‘sentir-se só’ ou
‘sentir-se bem-vindo’, e com base nisso ‘sentimos que nos apetece dar
uma volta’ ou ‘sentimos vontade de visitar determinada pessoa’: há
uma propensão. Alguém nos diz algo e podemos pensar, ‘Bem, isto soou-me
mesmo agressivo.’ Trata-se de um ‘significado sentido’, uma percepção
mental. Existe uma interpretação emotiva das palavras que alguém
proferiu e é provável que isso vá constituir a base para a intenção: as
nossas tendências, acções e reacções. O que ‘sentimos’ nisso, a
percepção, é uma impressão do coração (denominada ‘contacto-designação –
_adhivacana-phassa_). Apesar de se basear num contacto externo, este
contacto designação (ao contrário do contacto com algo externo) é o que
vai formular, de forma significativa, as impressões que nos animam. Uma
parte da intenção tem como base os reflexos do corpo mas, na sua maior
parte, trata-se da impressão do coração daquilo que é visto, ouvido,
cheirado, tocado ou pensado, que nos põe em movimento – para o bem e
para o mal.

O significado sentido torna-se mais poderoso se nós ‘sentimos’ que
alguém nos fez algo propositadamente, ao invés de o ter feito
acidentalmente ou por acaso. Imaginemos um caso em que uma pessoa foi
mal-educada para connosco catorze vezes este ano. Se o tivesse feito uma
vez, pensaríamos que tinha sido um engano, mas catorze vezes? A acção
actual foi sentida de forma mais intensa devido às acções que ocorreram
anteriormente. O ‘significado sentido’ desenvolve algum peso de forma
dependente de uma inferência emotiva. Podemos inferir intenção: ‘Ele
fez aquilo propositadamente’. Ou fatalismo: ‘Tenho sempre de aturar
pessoas estouvadas’. Podemos reagir em conformidade a nível
psicológico, verbal ou físico. Esta é a forma como impressões, atitudes
e tomadas de posição prévias moldam a impressão do coração. Desta
maneira, as impressões e as atitudes que transportamos do passado
tornam-se uma base para a intenção, uma base para mais _kamma_.

Do mesmo modo, quanto mais nos centramos nas nossas impressões e lhes
damos atenção, ou vemos o mundo e os outros através de impressões
antigas, mais essas impressões podem ficar potentes e firmemente
estabelecidas. Mas não podemos confiar nas impressões do coração. Isto
acontece porque temos a tendência para reparar naquilo que nos
habituamos a reparar: a conduta graciosa dela, os maneirismos irritantes
dele, etc. E, à medida que revisitamos o mundo desta forma,
acrescentamos mais interpretações. Então, eu ‘sinto’ que ‘ele é
sempre assim’ ou eu ‘vejo-te’ de uma determinada forma, ou eu apenas
reparo nos meus maus hábitos. Deste modo o meu foco, a minha atenção,
fica preparada para procurar impressões antigas. E eu trago-as à mente,
matuto sobre elas, sou afectado por elas e ajo em conformidade. De forma
que a mente que perscruta consegue estar sempre a selecionar impressões
de acordo com a tendência do coração e, desta maneira, a contribuir para
essa tendência, intensificando-a. A atenção está, deste modo, também
ligada à intenção e à geração do kamma. Isto tudo significa que não
podemos confiar apenas no coração ou apenas na atenção. Temos de
cultivar uma atenção cuidadosa, atentos ao coração, de forma a chegar ao
fim das tendências preconcebidas.

== Compreensão, atenção cuidadosa e consciência plena

Tendo tudo isto em consideração, como é que podemos examinar e responder
de forma mais adequada? Como é que podemos reconhecer que sentimos que
nos estão a prejudicar ou a maltratar e não simplesmente reagirmos ou
suprimirmos? Talvez precisemos de dizer umas quantas coisas a algumas
pessoas… ou talvez seja apenas uma questão de corrigirmos as nossas
próprias percepções erróneas… Em qualquer dos casos, a melhor forma de
começar é por examinar o coração. Este processo inicia-se com a
‘atenção compreensiva’ (_yoniso manasikārā_), que se traduz na atenção
reforçada pela intenção em considerar a experiência em termos da forma
como esta nos afecta. É uma abordagem feita de coração, através da qual,
ao invés de apenas seguirmos o tópico de um pensamento, o ouvimos
profundamente. Passamos a pente fino a torrente de interpretações ou de
divagações à volta dos tópicos com um sentido inquisitório que
interroga: ‘Qual o significado subjacente a este pensamento ou a esta
atitude? Qual a suposição e até que ponto é realista? Em que estado me
encontro com a minha mente desta forma?’ Trata-se de um inquérito
compassivo e não crítico. E este inquérito pede-nos para termos um
sentimento preciso sobre as psicologias que dirigem a nossa vida.
Seguidamente: ‘Gera stress ou não?’

Este processo revela os impulsos e as impressões subjacentes do coração
– se se trata de sentimentos de ameaça ou alienação, ou de encorajamento
e confiança. Este material subjacente é o motor que fornece energia para
a forma como pensamos e para aquilo sobre o qual pensamos. É importante
sabermos o que nos faz agir em qualquer situação, de modo que controlar
este processo não constitui uma supressão – trata-se mais de
permitirmo-nos examinar o nosso território interior. Isto ajuda-nos a
ver para além das fronteiras da nossa percepção de nós próprios. Mas
colocamos a análise e a acção sob pausa: não tentamos corrigir as
coisas; não vamos cair compulsivamente numa opinião sobre nós próprios
baseada neste inquérito. E a beleza simples deste processo é que, quando
suspendemos as reacções sobre o que devíamos e não devíamos estar a
sentir, existe clareza e amplitude. Com isto voltamos a conectar-nos com
a nossa sensibilidade ética inata – o bom kamma que constitui um suporte
à clareza e à compaixão.

Estas, felizmente, são as qualidades básicas que todos possuímos
enquanto seres humanos. Mas, porque a nossa forma de abordagem é muitas
vezes superficial, ou sujeita aos nossos objetivos, estas qualidades nem
sempre nos são acessíveis. Assim, elas surgem em virtude de uma
consideração abnegada, uma consideração sem pressões, opiniões ou juízos
de valor. Esta consideração é a atenção compreensiva. Apenas tenta ver
aquilo que é stressante e aquilo que precisamos de largar. E esta
simples franqueza interior é, muitas vezes, tudo o que na realidade
precisamos – em geral, quando temos este ponto de vista, podemos
destrinçar os detalhes do que fazer e como fazer, ou de não fazermos
seja o que for.

Um outro desenvolvimento da atenção é a consciência estabelecida
(_sati_) – a capacidade para manter em mente um tema, uma disposição, um
pensamento ou uma sensação. Trata-se de uma utilização adequada da
_mano_, a mente-órgão. Enquanto que a atenção compreensiva é uma atenção
activa que passa os tópicos da mente a pente fino, a consciência
estabelecida mantém a atenção num ponto – num pensamento ou numa
sensação – de forma a olhar para a natureza deste ou desta enquanto
fenómeno. Por exemplo, a consciência estabelecida tem em conta uma
emoção enquanto emoção e não deixa que esta se consolide numa atitude ou
numa acção. Mantém a fronteira do momento presente, de forma que
conseguimos realmente discernir o que é um sentimento e o que é uma
disposição, em vez de agirmos com base neles, de os tentar explicar ou
suprimir. A consciência estabelecida é vital, uma vez que ao nível das
sensações não existem fronteiras – as sensações mentais vão a todo o
lado. E se esse sentimento começa a proliferar, torna-se ‘Eu sou.
Sempre serei. As pessoas não gostam de mim. Sou terrível…’ – e vai
continuando a ressoar. Mesmo no caso de uma disposição positiva, se a
consciência estabelecida se encontra ausente, podemos partir do
princípio de que tudo é fantástico e sermos bastante insensíveis às
disposições dos outros. Por isso é sempre bom estabilizar o domínio da
_citta_ com a consciência estabelecida. Assim, não nos prendemos à
percepção e ao sentimento, e não proliferamos à volta das impressões do
coração ou de estados da mente que podem surgir subsequentemente.

Um complemento para a consciência estabelecida é a ‘consciência plena’
(_sampajañña_). A consciência plena é a capacidade de estarmos atentos e
receptivos, a capacidade de termos noção e compreendermos aquilo a que
somos sensíveis. É baseado na _citta_. A consciência estabelecida mantém
uma fronteira, de forma a não ficarmos assoberbados, fechados ou a
reagirmos aos sentimentos que temos. Então, com a consciência plena,
compreendemos o todo, compreendemos como as impressões surgem e o que
fazem. Podemos então perceber: ‘este sentimento ou esta impressão
baseia-se nesta percepção e neste pensamento, e desaparece quando esse
pensamento ou essa percepção são retirados.’ ‘Esta impressão negativa
surge com aquela percepção ou aquela memória, e desaparece quando eu
ponho em prática a benquerença, ou até mesmo quando consigo apenas
observá-la e deixá-la desaparecer.’ A consciência estabelecida e a
consciência plena, em conjunto, reconhecem o que está a acontecer e onde
acaba. Elas não trazem o ‘eu sou’ nem o ‘eu devia ser’ para a
equação.

Se instituirmos estas capacidades conscientes, elas libertam a mente de
agir na sequência dos resultados do passado, ou de reagir a estes. Se
prestamos atenção às impressões actuais, às disposições e sensações
actuais, e cortarmos as proliferações e as projecções, não vivemos na
névoa do ressentimento, da fantasia, do romance e de outras ideias
preconcebidas. Isto significa que a nossa atenção e, consequentemente,
as nossas disposições, acções e discurso, vão ser mais claros e
luminosos. Devido a isto, podemos ficar mais libertos da nossa acção
habitual – ou inacção. (Privarmo-nos de agir é, ainda assim, uma acção –
e isso torna-se igualmente um hábito!) Mas se estamos cuidadosamente
atentos ao coração, podemos falar sobre como as coisas parecem, que
incidentes deram origem ao ‘sentimento’ de sermos maltratados, e ter
uma sensação de que, independentemente de mais alguém escutar ou
responder ou não, pelo menos trouxemos alguma clareza às nossas vidas.
Não temos de estar a criar novo kamma com base nos hábitos antigos – a
atenção sábia é o kamma que conduz ao fim do kamma.

== Atenção que guarda e que tranquiliza

Estabelecer presença de mente e total consciência na vida quotidiana
requer uma filtragem cuidada da informação que nos chega de todas as
direcções, uma vez que o simples dilúvio do contacto pode ser
avassalador. O contacto é uma forma de kamma: aquilo a que damos atenção
recebe a nossa energia e entra nos nossos corações, onde estimula a
acção e a reacção.footnote:[“… seja o que for que um bhikkhu pensa e
pondera com frequência, isso irá tornar-se a tendência da sua mente. Se
ele pensa com frequência e pondera sobre pensamentos de renúncia, boa
vontade… inofensividade, então a sua mente tende para a renúncia, boa
vontade… inofensividade.” https://suttacentral.net/mn19/en/bodhi[MN
19.8]] Uma vez que, em consequência disto, desenvolvemos hábitos claros
ou escuros, temos de ser responsáveis relativamente àquilo a que damos
atenção. Parte deste cultivo envolve, desta forma, virar costas a
informação e material que leva a mente para o anseio, para a aversão ou
para a distração. Por isso, uma outra função do discernimento é ser
discriminativo: ter intenção, verificar, passar a pente fino, deitar
fora a escória e reter o ouro.

Na realidade, em vez de ter a mente absorvida seja no que for que os
meios de informação estão a despejar, existem temas aos quais é bom dar
atenção.footnote:[“E quais são as coisas dignas de atenção às quais ele
se dedica? Trata-se de coisas cuja natureza faz com que (quando ele se
dedica a elas): a mácula ausente do desejo sensual não surge e a mácula
presente do desejo sensual é abandonada, a mácula ausente do devir não
surge… e a mácula presente do devir é abandonada, a mácula ausente da
ignorância não surge… e a mácula presente da ignorância é abandonada.”
https://suttacentral.net/mn2/en/bodhi[MN 2.10]] A compreensão tem a ver
com a reflexão. Existem variadas reflexões, mas reflectir é algo que
podemos fazer durante o dia. Antes de mais existe a mortalidade, e ao
considerarmos o facto da mortalidade de forma cuidadosa e abnegada,
estamos a ajudar a mente a manter-se calma e estável – não ficamos
imprudentes ou egoístas e não mantemos ressentimentos. A percepção da
mortalidade leva a que algumas das coisas que nos prendem percam a sua
força. Onde é que está a pressão para obter ou para ser algo quando
perdemos tudo o que alcançamos? Ao que é que vale realmente a pena dar
atenção e tempo? A recordação da mortalidade também nos lembra que os
nossos recursos, a nossa energia, a nossa capacidade mental e a nossa
saúde são finitos e em declínio. Podemos usar os nossos recursos de uma
forma que vá potenciar ou libertar as nossas vidas ou podemos
desperdiçar tempo com fantasias e frustrações. Então, usada de forma
sábia, a lembrança e reflecção sobre a morte mantém a mente em forma,
limpa e presente. Diz-nos que é tempo de largar o nosso fardo.

Outra característica positiva que decorre ao reflectirmos sobre a
mortalidade é a empatia. Uma das maiores fontes de sofrimento, e base
para o _kamma_ negativo, é a perda de empatia para com os outros. Na
vida urbana moderna, podemos experienciar muitas pessoas através dos
estereótipos mediáticos, ou na ‘terra de ninguém’ das ruas agitadas e
locais públicos. As pessoas tornam-se, desta forma, ‘outros’ - outras
nacionalidades, outras religiões, etc. – e nós podemos sentir
indiferença ou desconfiança em relação a elas. Num campo emocional com
este tipo de enviesamento, a indiferença e até a brutalidade encontram
terreno fértil para proliferar. Mas se tivermos em consideração o nosso
terreno comum – que, como nós, também os outros passam por tensão,
doença, perda e morte – é mais fácil gerar-se empatia. Por exemplo, um
dos monges mencionou que sempre que a vida está a tornar-se um pouco
tensa e ele começa a sentir-se irritável ou a perder a perspetiva, ele
olha para imagens de vítimas de fome e de pessoas com doenças e
deformidades terríveis. Então experiencia um sentimento de compaixão
pelo reino humano, bem como gratidão pela enorme bênção que é ser
saudável, livre de penúria, bem alimentado e cuidado. A reflexão evoca
um estado que ao ser mantido conscientemente, pode vir a tornar-se um
local estável de permanência para o coração. Então a rudez, a
indiferença e a autocomiseração não prevalecem.

Podemos igualmente alargar a empatia de forma a nos lembrarmos que os
outros também têm alegria e desespero, humor e medo, nascimento,
famílias e o seu kamma… Então, porque é que eu não percebo os outros da
mesma forma como eu gostaria que eles me percebessem? A moralidade, na
verdade, resume-se à empatia traduzida em formas de comportamento.

Considero muito útil meditar sobre os ‘outros’ e sobre aquilo que
suscitam em mim. E reparar que qualquer efeito que surge, surge na minha
própria mente afectiva – porque sou eu quem tem de viver com essa
indiferença, rudez ou empatia. Quando o coração é defensivo ou
displicente, fica apertado, oprimido, e não consegue aceder à energia
que me dá suporte. E quanto mais me sinto pesado e contraído
relativamente aos outros, mais pesada e contraída fica a minha vida.
Evidentemente que abrir o coração traz todo o tipo de irritações e de
medos condicionados mas, se existe atenção compreensiva, o coração
também tem acesso à coragem e à compaixão que constituem o seu
potencial. E, à medida que me sintonizo com o tema do bom kamma da
condição humana, posso realmente apreciar e saborear a nutrição
proporcionada pela bondade, pelo cuidado protector da compaixão, pela
alegria do reconhecimento e pela equanimidade, de forma a manter o
espaço que permite às emoções movimentarem-se. A empatia dá-me acesso à
minha sanidade inata.

== Imagens do Despertar

De forma a alegrar o coração, é bom trazer à mente uma imagem ou um
tópico. Geralmente o mais útil é a recordação das qualidades das pessoas
que fazem parte da nossa vida, porque nós aprendemos muito sobre o kamma
luminoso através da observação das acções dos outros. Assim, um dos
maiores apoios para o Despertar é ter relacionamentos significativos com
as outras pessoas. Isto pode incluir os nossos pais, amigos ou pares,
que representam ou invocam os nossos sentimentos de gratidão,
integridade, compaixão – valor. Sem pontos de referência humanos, vivos
ou já falecidos, a mente está a lidar com abstracções, inclusive em
relação a si própria. As pessoas isoladas ficam presas a noções
irrealistas delas próprias, ou a passatempos, planos, aparelhos ou
várias formas de entretenimento. Não existe um sentimento de ligação ou
de fazer parte de algo maior do que nós. Isso constitui uma perda
enorme.

Para trabalhar contra isto, a lembrança do Sangha leva-nos à humanidade
da prática: não se trata apenas de algo que envolve um manual e algumas
ideias. Um dos principais benefícios de uma linhagem e de uma tradição é
despertar-nos para um sentido maior de nós próprios – para a partilha da
camaradagem espiritual com pessoas boas, pelo mundo inteiro, através dos
tempos. Podemos igualmente recordar a partilha de um sistema de valores
que dá um grande significado ao kamma: é esta a lembrança do Dhamma. De
modo que recordamos a aspiração e o Despertar como a nossa referência
comum, e o sofrimento e o mal-estar como o nosso desafio comum. Então
deixamos de nos sentir tão sós com os nossos estados mentais difíceis e
conseguimos lidar com eles de uma forma mais aberta e consciente. A
recordação do Dhamma e do Sangha lembra-nos que, apesar de existirem
avidez, zanga e confusão, existe sempre uma forma de lidar com elas, que
nos leva além desse âmbito. E existem pessoas que percorreram esse
caminho.

O próprio contexto da prática pode ser elevado através da utilização de
altares, de oferendas a uma imagem do Buddha e da entoação de cânticos.
Isto constitui o _puja_: o acto de prestar homenagem ao Buddha, trazendo
à mente o milagre do Despertar numa forma corpórea. Mas não se trata de
adorar uma imagem. Nós utilizamos o ritual porque isso nos dá a
oportunidade de agir, ao invés de pensar, e podemos fazê-lo em conjunto,
através do corpo, do pensamento e do coração. Uma acção de grupo eleva o
sentimento de participação no significado do Despertar. Uma sintonização
e uma participação plenas levam-nos para fora do nosso pequeno ‘eu’ e
proporcionam uma ressonância profunda.

É por esta razão que, num mosteiro, temos uma imagem tangível e
manifesta do Buddha. É algo que podemos tratar respeitosamente –
limpá-la fisicamente, iluminá-la com luzes, oferecer-lhe flores. Luzes
suaves, flores e gestos de oferendas encorajam a atenção a permanecer no
sentimento do coração em relação ao altar e, desta forma, a mente é
tocada pelo sentimento de estabilidade, de tranquilidade ou de
radiância, e pode permanecer aí. Se estas impressões e significados
sentidos forem estabelecidos de forma regular, atinge-se um ponto no
qual a simples visão de uma imagem do Buddha eleva o espírito ou acalma
a mente.

Entoar cânticos, particularmente em grupo, pode ter um efeito de
harmonização, de acalmia: de forma sonora e pausada, pode ajudar-nos
verdadeiramente a apreciar os nossos companheiros de prática. Aqui
estamos nós – pelo menos desta vez sem os nossos nomes e histórias –
seres humanos que têm como intenção estar plenamente conscientes. Então
temos a noção da nossa própria presença inserida numa perspetiva mais
abrangente. De certa forma, continua a ser somente o nosso corpo e a
nossa mente com todas as suas idiossincrasias, mas a recordação/reflexão
leva a um conhecimento empático de tudo isso.

== O não envolvimento necessita de apoio

A atenção compreensiva é, desta forma, uma acção que nos faz parar e que
nos leva, mais profundamente, para as nossas mentes e para os nossos
corações. Isto prepara-nos para a meditação. Se começamos a meditar a
partir de um ponto escuro ou turvo, a consciência estabelecida e a
consciência plenas são fracas. Podemos dizer a nós próprios que ser
escuro ou turvo é sermos autênticos e que devemos apenas estar
conscientes disso. O que, de certa forma, é verdade. Contudo, as
memórias, os planos, as preocupações e os ressentimentos, em geral, são
tão poderosos que em vez de estarmos conscientes deles, eles capturam a
nossa atenção e tornam-se obsessivos. Assim, é importante estabelecermos
um foco com a visão correcta – termos em mente como estamos a ser
afectados por aquilo ao qual estamos a dar atenção. É inútil
despendermos tempo com a nossa atenção aprisionada por preocupações ou
ressentimentos. Sentarmo-nos sem recursos para o coração não é
meditação.

É mais produtivo entrar na meditação através da compreensão, até mesmo
ponderando e considerando de que forma a mente está a ser afectada pelas
coisas. Ou seja, nós lidamos com a mente de modo cordial, examinamos e
discernimos: ‘O que traz sofrimento e tensão? O que os faz soltar?’
Esta intenção traz uma consciência que apoia a sabedoria do Despertar:
olhar para o mal-estar e para a libertação do mal-estar. A consciência
apenas mantém as coisas em mente. Assim, para o Despertar, o
coração-base precisa de ser apoiado pela intenção correcta – que resulta
da atenção compreensiva e da consciência plena.

A prática não irá longe se a acção da mente não estiver a agir com base
em compromisso, ética e destreza. Mas o cultivo da mente de acordo com
estas directrizes, é um apoio para a compreensão, a atenção e a
consciência. Então conseguimos enfrentar estados positivos, estados
negativos ou estados ‘assim assim’, e encontrar sabedoria e
libertação. Porque o que é essencial em todos os casos é que exista uma
distanciação consciente do impulso de um hábito ou da inclinação de uma
disposição emotiva. Isto leva a um apaziguamento da intensidade e do
impulso do estado de espírito, de forma que existe um enfraquecimento
momentâneo ou o finalizar do kamma. Esta mudança acontece quando somos
claros e honestos: não acontece se estamos a esconder alguma coisa ou a
tentar fazer com que algo aconteça – incluindo estarmos a tentar ser
desapegados! Isto é assim porque a mudança implica afastarmo-nos da
tentativa de encontrarmos ou de sermos algo, e de sermos íntegros e
claros perante as nossas questões. E o bem que já fizemos, a nossa
paciência e a nossa honestidade, contribuem para fortalecermos a
mente-base de forma a tornar esse distanciamento possível.

Assim, quando existe escuridão no coração, sabemos como lidar com ela de
forma sensata. Não temos de descobrir qual a sua origem e quem tem
responsabilidade. Talvez provenha de alguma acção passada ou talvez seja
um hábito crítico e negativo, que cria no presente uma memória ou uma
interpretação. Mas tudo o que temos de saber é que isso é _vipāka_
escuro e onde é que ele se desvanece. Diria que o processo é quase como
colocar uma peça de roupa suja num lago. A limpeza é realizada
simultaneamente pela acção de colocar a peça de roupa no lago e pela
ausência de acção – uma vez que a água trata da limpeza. Pegamos nesse
resíduo escuro e colocamo-lo seja em que clareza ou pureza possa existir
e, apesar de termos de esfregar bem os bocados mais encardidos, é a
nossa sanidade básica que lava a sujidade.

Estabelecemo-nos num estado desperto e então a consciência continua a
experienciá-lo, a senti-lo, e a deixar ir aquilo que surge. Quando algum
resíduo escuro é removido, a plena consciência sente a leveza, a
luminosidade. E podemos sintonizar-nos com isso. Ao longo do tempo, à
medida que vamos cultivando isto, desenvolve-se uma crescente base de
bem-estar, uma luminosidade na qual podemos permanecer. Mas devido ao
facto de não existir um sentimento de ‘eu fiz isto’ ou de ‘eu vou
conseguir isto’, a mente não fica enfatuada, permanecendo tranquila e
receptiva.

De facto, qualquer tipo de opinião sobre nós próprios só confunde pois,
como nos apercebemos na meditação, ficarmos presos nos pensamentos e
disposições não depende de uma decisão pessoal. E também não se trata de
‘eu não estou apegado’. Imaginemos que a mente se encontra ampla e
estável e nisto surgem pensamentos sobre o nosso futuro, ou
relativamente a alguém que nos está a dificultar a vida e, de repente,
lá estamos, a apertarmo-nos, a apressarmo-nos e a proliferarmos acerca
de tudo isto. E surge a opinião relativamente a quem é o culpado… e
sobre o que devemos fazer… e porquê eu… Isto começa com uma tendência,
avança para uma acção e depois torna-se uma pessoa. De forma que a
libertação não pode ser atingida através de um eu aparente que tem, ou
devia ter, o controlo. Ao invés, requer as capacidades de uma atenção
que consegue lidar com o kamma antigo à medida que este vem à tona.

A nossa prática é assim conduzida pelo Dhamma e não pelas nossas
opiniões sobre nós próprios, direccionando-se tendencialmente para o
término do que é antigo, em vez de nos tornar em algo novo. Trata-se de
um cultivo que nos liberta e protege, e nos faz convergir para um espaço
livre no centro da vida. É o kamma que leva ao fim do kamma e tem o
sabor da liberdade.

== Meditação

_Recordar_

Sente-se com uma postura alerta e verticalizada, que permita ao corpo
estar confortável e sem se remexer, mas que encoraje a vigília. Deixe os
seus olhos se fecharem ou semicerrarem. Traga o foco da mente
conscientemente ao corpo, sentindo o seu peso, as suas pressões,
pulsações e ritmos. Traga à mente a sugestão de se estabelecer onde se
encontra neste momento e pôr de lado, por agora, outras preocupações ou
interesses.

Realize algumas expirações lentas e longas, a sentir a sua respiração a
sair para o espaço que o rodeia. Deixe que a inspiração comece por si
própria. Sinta como a inspiração vai buscar o ar ao espaço à sua volta.
Entre em sintonia com o ritmo desse processo e interrompa quaisquer
pensamentos que o distraiam através do restabelecimento da sua atenção
em cada expiração.

Traga à mente qualquer exemplo de acções de pessoas que o tenham tocado
de uma forma positiva, em termos de bondade, paciência ou compreensão.
De forma repetida, toque o coração com alguns exemplos específicos,
estabelecendo-se no sentimento que evocam.

Permaneça, durante um minuto ou dois, com a sua recordação mais
profunda, cultivando uma atitude de curiosidade: ‘Como é que isto me
afecta?’ Aperceba-se de qualquer efeito no coração: pode haver uma
qualidade de elevação, de acalmia ou de firmeza. Pode mesmo detectar uma
alteração no tónus global do corpo. Dê-se a si próprio todo o tempo para
estar aqui, sem qualquer objectivo específico para além de sentir como
se relaciona com o momento, numa atitude de compaixão observadora.

Estabeleça-se nesse sentimento e concentre-se em particular na
tonalidade da disposição, que pode ser de luminosidade, de estabilidade
ou de elevação. Ponha de lado o pensamento analítico. Permita que, na
mente, quaisquer imagens surjam e desapareçam. Permaneça e expanda a
consciência da sensação de vitalidade ou de tranquilidade, conforto,
espaço ou luz.

De acordo com o tempo e a energia, conclua o processo sentindo
plenamente quem ‘você é’ nesse estado. Primeiro sinta como está em
termos físicos. Seguidamente note quais as tendências e as atitudes que
parecem naturais e importantes, quando permanece nesse seu local
meritório. Seguidamente leve essas tendências e atitudes para a sua
situação do dia a dia interrogando-se: ‘O que é importante para mim
neste momento?’, ’O que tem maior importância?’ Depois dê-se tempo a si
próprio para que as prioridades da acção se estabeleçam de acordo com a
resposta.
