[#titlepage]
= {booktitle}

[role=titlepage-author]
{author}

image::{pubs-logo}[role=titlepage-pubs-logo]

[role=titlepage-publisher]
{publisher-name}

[role=titlepage-publisher-website]
link:{publisher-link-url}[{publisher-link-name}]

<<<<<<<<

[quote, role=quote]
____
Dedicado a

Goeren e Kyllie Lindeblad

e Patricia Buckle
____

<<<<<<<<

[quote, role=quote]
____
“O kamma deve ser conhecido.
A causa através da qual o kamma entra em acção deve ser conhecida. A diversidade no kamma deve ser conhecida. O resultado do kamma deve ser conhecido. A cessação do kamma deve ser conhecida. O caminho da prática que leva à cessação do kamma deve ser conhecido. Assim foi dito. Por que razão foi dito?

A intenção, digo-vos, é kamma. Ao termos intenção, produzimos kamma através do corpo, da fala e da mente.

E qual a causa através da qual o kamma entra em acção?

O contacto, bhikkhus.

E o que é a diversidade no kamma? Existe kamma a ser experienciado no inferno, kamma a ser experienciado no reino dos animais vulgares, kamma a ser experienciado no reino das sombras famintas, kamma a ser experienciado no mundo humano, kamma a ser experienciado nos mundos celestiais.

E qual é o resultado do kamma? O resultado do kamma, digo-vos, tem três tipos: aquele que surge aqui e agora, aquele que surge mais tarde (nesta vida) e aquele que surge depois disso…

E o que é a cessação do kamma? A partir da cessação do contacto dá-se a cessação do kamma e apenas este nobre caminho óctuplo – visão correcta, propósito correcto, discurso correcto, acção correcta, meio de subsistência correcto, esforço correcto, consciência correcta, concentração correcta – constitui o caminho da prática que conduz à cessação do kamma.

Assim, quando um discípulo dos seres nobres compreende desta forma o kamma, a causa através da qual o kamma entra em acção, a diversidade no kamma, o resultado do kamma, a cessação do kamma e o caminho da prática que conduz à cessação do kamma, então compreende esta vida sagrada penetrante como a cessação do kamma.

‘O kamma deve ser conhecido. A causa através da qual o kamma entra em acção … A diversidade no kamma … O resultado do kamma … A cessação do kamma … O caminho da prática que leva à cessação do kamma …’ Assim foi dito e esta é a razão pela qual foi dito.”

_https://suttacentral.net/an6.63/en/thanissaro[AN 6.63]_
____
